export enum ACTIONS_TYPE {
	REQUEST = <any>'_REQUEST',
	FAILURE = <any>'_FAILURE'
}

enum ACTIONS {
	EDIT_PLACES = <any>'EDIT_PLACES',
	SELECT_PLACES = <any>'SELECT_PLACES',
	SELECT_SERVICE = <any>'SELECT_SERVICE',
	SELECT_MATERIAL = <any>'SELECT_MATERIAL',
	SAVE = <any>'SAVE',
	NEED_PLACES = <any>'NEED_PLACES',
}

export default ACTIONS;
