export enum ACTIONS_TYPE {
	REQUEST = <any>'_REQUEST',
	FAILURE = <any>'_FAILURE'
}

export enum ACTIONS {
	API_NEED_DETAILS = <any>'API_NEED_DETAILS',
	API_NEED_SERVICES = <any>'API_NEED_SERVICES',
	API_NEED_MATERIALS = <any>'API_NEED_MATERIALS',
	API_NEED_COLORS = <any>'API_NEED_COLORS',

	API_NEED_PRODUCERS = <any>'API_NEED_PRODUCERS',
	API_ADD_NEW_PRODUCER = <any>'API_ADD_NEW_PRODUCER',
	API_REMOVE_PRODUCER = <any>'API_REMOVE_PRODUCER',
	API_SAVE_PRODUCER = <any>'API_SAVE_PRODUCER',

	API_NEED_THICKNESS = <any>'API_NEED_THICKNESS',
	API_NEED_OPACITY = <any>'API_NEED_OPACITY',

	EDIT_PLACES = <any>'EDIT_PLACES',
	SELECT_PLACES = <any>'SELECT_PLACES',
	SELECT_SERVICE = <any>'SELECT_SERVICE',
	SELECT_MATERIAL = <any>'SELECT_MATERIAL',
	SAVE = <any>'SAVE',
	NEED_PLACES = <any>'NEED_PLACES',
	NEED_SERVICES = <any>'NEED_SERVICES',
}

export default ACTIONS;
